import Head from 'next/head';
import { useState } from 'react';
import { Button } from '../components/button';
import { CardBody, CardLoad } from '../components/card';
import {
  ContainerCards,
  ContainerContent,
  FormStyled,
} from '../components/container';
import InputWall from '../components/inputWall';
import { LoadingCircle } from '../components/loading';
import { Label, SubTitle, Title } from '../components/typograph';
import { wall } from '../types/inputTypes';

export default function Home() {
  const [stage, setStage] = useState('RESULT');
  const [wallOne, setWallOne] = useState<wall>({} as wall);
  const [wallTwo, setWallTwo] = useState<wall>({} as wall);
  const [wallThree, setWallThree] = useState<wall>({} as wall);
  const [wallFour, setWallFour] = useState<wall>({} as wall);
  const [result, setResult] = useState();

  const wallsConfig = [
    {
      title: 'Wall 01',
      value: wallOne,
      setValue: setWallOne,
    },
    {
      title: 'Wall 02',
      value: wallTwo,
      setValue: setWallTwo,
    },
    {
      title: 'Wall 03',
      value: wallThree,
      setValue: setWallThree,
    },
    {
      title: 'Wall 04',
      value: wallFour,
      setValue: setWallFour,
    },
  ];

  function ViewStages() {
    switch (stage) {
      case 'INITIAL':
        return (
          <FormStyled>
            <ContainerCards>
              {wallsConfig.map(({ title, value, setValue }) => (
                <CardBody key={title}>
                  <InputWall title={title} wall={value} setWall={setValue} />
                </CardBody>
              ))}
            </ContainerCards>
            <Button>Submit</Button>
          </FormStyled>
        );
      case 'LOAD':
        return (
          <CardLoad>
            <LoadingCircle />
          </CardLoad>
        );

      case 'RESULT':
        // {
        //   "majorPaintCanQuantity": 0,
        //   "mediumPaintCanQuantity": 0,
        //   "minorPaintCanQuantity": 1,
        //   "smallPaintCanQuantity": 1
        // }
        return (
          <>
            <CardBody>
              <SubTitle>Result</SubTitle>
              {result?.majorPaintCanQuantity && (
                <Label>
                  {' '}
                  <span>{result?.majorPaintCanQuantity}</span>
                </Label>
              )}
            </CardBody>
            <Button>Return</Button>
          </>
        );
    }
  }

  return (
    <div>
      <Head>
        <title>Challenger Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContainerContent>
        <Title>Paint Calculator</Title>
        {ViewStages()}
      </ContainerContent>
    </div>
  );
}
