import Head from 'next/head';
import { useState } from 'react';
import { CardBody } from '../components/card';
import { ContainerCards, ContainerContent } from '../components/container';
import InputWall from '../components/inputWall';
import { Title } from '../components/typograph';
import { wall } from '../types/inputTypes';

export default function Home() {
  const [wallOne, setWallOne] = useState<wall>({} as wall);
  const [wallTwo, setWallTwo] = useState<wall>({} as wall);
  const [wallThree, setWallThree] = useState<wall>({} as wall);
  const [wallFour, setWallFour] = useState<wall>({} as wall);
  return (
    <div>
      <Head>
        <title>Challenger Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContainerContent>
        <Title>Paint Calculator</Title>

        <ContainerCards>
          <CardBody>
            <InputWall wall={wallOne} setWall={setWallOne} />
          </CardBody>
          <CardBody>
            <InputWall wall={wallTwo} setWall={setWallTwo} />
          </CardBody>
          <CardBody>
            <InputWall wall={wallThree} setWall={setWallThree} />
          </CardBody>
          <CardBody>
            <InputWall wall={wallFour} setWall={setWallFour} />
          </CardBody>
        </ContainerCards>
      </ContainerContent>
    </div>
  );
}
